#!/bin/bash
# chkconfig: 2345 90 10
# description: A secure socks5 proxy, designed to protect your Internet traffic.

### BEGIN INIT INFO
# Provides:          ShadowsocksR
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fast tunnel proxy that helps you bypass firewalls
# Description:       Start or stop the ShadowsocksR server
### END INIT INFO

if [ -f /etc/shadowsocks-r/config.json ]; then
    CONF=/etc/shadowsocks-r/config.json
elif [ -f /etc/shadowsocks.json ]; then
    CONF=/etc/shadowsocks.json
fi
NAME=ShadowsocksR
DAEMON=/usr/local/shadowsocks/server.py

check_running() {
    PID=$(ps -ef | grep -v grep | grep -i "${DAEMON}" | awk '{print $2}')
    if [ -n "$PID" ]; then
        return 0
    else
        return 1
    fi
}

do_start() {
    if check_running ; then
        echo "$NAME (pid $PID) is already running..."
        exit 0
    else
        if "$DAEMON" -c "$CONF" -d start ; then
            echo "Starting $NAME success"
        else
            echo "Starting $NAME failed"
            return 1
        fi
    fi
}

do_stop() {
    if check_running ; then
        if "$DAEMON" -c "$CONF" -d stop ; then
            echo "Stopping $NAME success"
        else
            echo "Stopping $NAME failed"
            return 1
        fi
    else
        echo "$NAME is stopped"
        return 1
    fi
}

do_status() {
    if check_running ; then
        echo "$NAME (pid $PID) is running..."
    else
        echo "$NAME is stopped"
        return 1
    fi
}

do_restart() {
    do_stop
    sleep 0.5
    do_start
}

case $1 in
start | stop | restart | status)
    "do_$1"
    ;;
*)
    echo "Usage: $0 { start | stop | restart | status }"
    exit 1
    ;;
esac
